drop table tblReview;
drop table TblItemCostHistory;
drop table TblShipLine;
drop table TblItemLocation
drop table TblOrderLine;
drop table TblItem;
drop table tblItemType;
drop table TblOrder;
drop table TblShipAddress;
drop table TblCustomer;
